### ISSUE TITLE
Remove redundant nil setters

### ISSUE THREAD

**Issue by plutov** [cyberhck/pushy#3]
https://github.com/cyberhck/pushy/blob/master/pushy.go#L123

I think in get/post/del functions it's not necessary to set `nil` in case of error, as by default all these vars are `nil`.

It will reduce code size.

**Comment by cyberhck** [comment]
Oh, yeah, I forgot to update those bits. I'll update this very soon.

backstory: at first it was returning values, so I was setting to nil, but now I'm writing to the address, but I forgot that bit.

thanks :slightly_smiling_face:
