### ISSUE TITLE
Do not skip Decode errors

### ISSUE THREAD

**Issue by plutov** [cyberhck/pushy#4]
https://github.com/cyberhck/pushy/blob/master/pushy.go#L157

```
json.NewDecoder(b).Decode(posRes)
```

has `error` as return value. Your function also returns error. I think it's better not to skip errors and do:

```
return json.NewDecoder(b).Decode(posRes)
```

**Comment by cyberhck** [comment]
Thanks,  I didn't think of that initially because pushy service team said that they're always gonna return in that format, but I'll keep that in mind and will add this fix very soon :slightly_smiling_face:
