### ISSUE TITLE
use fmt.Sprintf in url

### ISSUE THREAD

**Issue by plutov** [cyberhck/pushy#5]
https://github.com/cyberhck/pushy/blob/master/pushy.go#L51

I saw in other places you use `fmt.Sprintf`, can be used in all places to have code consistent.

Also, here `p.APIEndpoint` can be moved to Sprintf args and replaced by `%s`.

```
https://github.com/cyberhck/pushy/blob/master/pushy.go#L69
```

**Comment by cyberhck** [comment]
my bad, thanks. I'll update this soon quite likely tonight :slightly_smiling_face:
